positions:
# 	python3 process_image.py --image lens_corrected.jpg --pixels-per-meter 362.1
	python3 process_image.py --image lens_corrected.jpg 

analyze:
	python3 analyze_positions.py --original original_antenna_positions.json --pixels-per-meter 370
